name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tiobe-scan:
        name: TiCs-scan
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@e8084e0cc6409cda380d42632a858a8a511c5e4b # v2
        with:
            coverage-folder: .cover
            tiobe-project-name: pyroscope-operators
        secrets: inherit
